/**
 * Clarification Types
 *
 * Types for the pre-research clarification flow that generates questions,
 * collects answers, and creates an approved plan before deep research starts.
 */

import type { PlanTask } from "./core";

/**
 * Categories of clarification questions
 * - ambiguity: Vague terms, unclear scope, multiple interpretations
 * - data_requirements: Missing datasets, data sources, user's own data
 * - scope_constraints: Time period, species, tissue/organ, disease context
 * - methodology: Analysis approaches, literature focus, statistical methods
 * - output: Desired output format, deliverables, what the user wants from the research
 */
export type ClarificationCategory =
  | "ambiguity"
  | "data_requirements"
  | "scope_constraints"
  | "methodology"
  | "output";

/**
 * A single clarification question generated by the agent
 */
export interface ClarificationQuestion {
  category: ClarificationCategory;
  question: string;
  priority: "high" | "medium" | "low";
  context?: string; // Optional context explaining why this question is asked
}

/**
 * A user's answer to a clarification question
 */
export interface ClarificationAnswer {
  questionIndex: number;
  answer: string;
}

/**
 * A task in the initial research plan
 * Note: datasetFilenames stores just the names - actual dataset objects
 * are resolved at execution time from uploadedDatasets
 */
export interface ClarificationPlanTask {
  objective: string;
  type: "LITERATURE" | "ANALYSIS";
  datasetFilenames: string[]; // Filenames to match against uploadedDatasets at execution time
}

/**
 * The generated research plan based on clarification answers
 */
export interface ClarificationPlan {
  objective: string;
  initialTasks: ClarificationPlanTask[];
}

/**
 * An entry in the plan feedback history
 */
export interface PlanFeedbackEntry {
  feedback: string;
  previousPlan: ClarificationPlan;
  regeneratedPlan?: ClarificationPlan;
  timestamp: string;
  approved: boolean;
}

/**
 * Database status enum for clarification sessions
 */
export type ClarificationStatus =
  | "questions_generated"
  | "answers_submitted"
  | "plan_generated"
  | "plan_approved"
  | "abandoned";

/**
 * Full clarification session record from database
 */
export interface ClarificationSession {
  id: string;
  user_id: string;
  conversation_id: string | null;
  initial_query: string;
  questions: ClarificationQuestion[];
  answers: ClarificationAnswer[];
  plan: ClarificationPlan | null;
  plan_feedback: PlanFeedbackEntry[];
  status: ClarificationStatus;
  created_at: string;
  updated_at: string;
}

/**
 * Context passed from clarification to deep research
 * Stored in conversationState.values.clarificationContext
 */
export interface ClarificationContext {
  sessionId: string;
  refinedObjective: string;
  questionsAndAnswers: Array<{
    question: string;
    answer: string;
  }>;
  initialTasks?: ClarificationPlanTask[]; // Tasks for first iteration (used once, then cleared)
}

/**
 * Input for creating a new clarification session
 */
export interface CreateClarificationSessionInput {
  userId: string;
  initialQuery: string;
  questions: ClarificationQuestion[];
}

/**
 * Input for submitting answers to a clarification session
 */
export interface SubmitClarificationAnswersInput {
  sessionId: string;
  answers: ClarificationAnswer[];
}

/**
 * Input for adding plan feedback
 */
export interface AddPlanFeedbackInput {
  sessionId: string;
  feedback: string;
  approved: boolean;
  regeneratedPlan?: ClarificationPlan;
}
